spring:
  application:
    name: est-spring-boot-java-erudio
  cors:
    originPatterns: http://localhost:8080,http://localhost:8081,http://localhost:8090,http://localhost:3000
  # Configurações do Banco de Dados
  datasource:
#    utilizar para producao
#    url: jdbc:mysql://host.docker.internal:3306/rest_spring_boot_jzbreno?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/rest_spring_boot_jzbreno?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
    #docker run -e SPRING_DATASOURCE_USERNAME=root -e SPRING_DATASOURCE_PASSWORD=admin123 -e SPRING_DATASOURCE_URL="jdbc:mysql://host.docker.internal:3306/rest_spring_boot_jzbreno?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true" -p 8080:8080 -d jzbreno/est-spring-boot-java-erudio:0.0.1-SNAPSHOT
  # Configurações do JPA e Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  # ONDE ADICIONAR A CORREÇÃO TEMPORÁRIA DO FLYWAY:
  flyway:
    # Esta linha forçará o Flyway a corrigir o checksum da V5 falhada
    repair-on-migrate: true
    clean-disabled: false
    clean-before-validation: true
# Local correto para definir o nível de log
logging:
  level:
    #configurando para toda aplicacao rodar em nivel de WARN
    root: INFO
    # Aumenta o nível de log para o seu pacote
    br.com.jzbreno: DEBUG
    # Opcional: Para ver logs de baixo nível do Spring
    # org.springframework: DEBUG

    #CONFIGURACAO DA DOCUMENTACAO SWAGGER
spring-doc:
  paths-to-match: {/person/**/**, /book/**/**, /pc/**/**}
  swagger-ui:
    use-root-path: true