spring:
  application:
    name: est-spring-boot-java-erudio
  cors:
    originPatterns: http://localhost:8080,http://localhost:8081,http://localhost:8090,http://localhost:3000
  datasource:
    url: jdbc:mysql://localhost:3306/rest_spring_boot_jzbreno?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  flyway:
    repair-on-migrate: true
    clean-disabled: false
    clean-before-validation: true

# CONFIGURAÇÕES FORA DO BLOCO SPRING
file:
  upload-dir: /Users/jzbre/OneDrive/Documentos/Desevolvimento/Projetos/Upload

logging:
  level:
    root: INFO
    br.com.jzbreno: DEBUG